hibernate:
  data:
    driver: org.postgresql.Driver
    username: postgres
    password: pass
    url: jdbc:postgresql://localhost:5432/postgres

spring:
  jpa:
    open-in-view: false
  liquibase:
    change-log: db/migration/changelog.yml

server:
  port: 8081