hibernate:
  data:
    driver: org.postgresql.Driver
    username: postgres
    password: pass
    url: jdbc:postgresql://localhost:5432/postgres

jwt:
  security:
    value: 9C6E7DE4B5A4D9245D6766BB3B17F

spring:
  jpa:
    open-in-view: false
  liquibase:
    change-log: db/migration/changelog.yml

server:
  port: 8081